# Generated by Django 3.0.5 on 2020-11-12 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default=None, upload_to='images')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 19, 42, 254206))),
                ('size', models.BigIntegerField()),
                ('accuracy', models.FloatField()),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
    ]
