# Generated by Django 3.0.3 on 2020-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nom_image',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
