# Generated by Django 3.0.3 on 2020-11-11 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20201111_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 16, 6, 55, 174585)),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
